// const { DataTypes, Sequelize } = require('sequelize');
// const db = require('../db_config/db');

// const UserConversations = db.define('UserConversations', {
//     userId: {
//       type: DataTypes.STRING,
//       references: {
//         model: 'Users', // Assuming Sequelize uses the default pluralized table name
//         key: 'username',
//       }
//     },
//     conversationId: {
//       type: DataTypes.INTEGER,
//       references: {
//         model: 'conversations', // Ensure this matches the actual table name generated by Sequelize
//         key: 'id',
//       }
//     }
//   }, {
//     // Additional model options
//   });

// module.exports = UserConversations